### ISSUE TITLE
Add support for --vault option

### ISSUE THREAD

**Issue by Tutelajoke** [zcutlip/pyonepassword#11]
Hi,

First off, thank you for putting this together. I am excited to soon be deprecating some pretty basic PowerShell and using this instead. However one bit of functionality my team needs is the ability to specify a vault. We have several, each corresponding to different deployment environments.

Cheers,
-Adam

**Comment by zcutlip** [comment]
Sweet, I'll try to have a look at that. I don't have a 1Password Teams account, but we do have a family account here; each of us with multiple vaults. Hopefully it works similarly.

It sounds like you're using it on Windows. Do let me know if you have problems there. I've only tested on macOS.

**Comment by Tutelajoke** [comment]
Right on. And yes, using it on Windows 10 quite successfully.

**Comment by zcutlip** [comment]
Can you list representative `op` commands that do what you want? Using those as a guide, I can be sure to add support to do the equivalent programatically.

E.g., 

- `op get item "kessel" --vault "Star Wars Planets"`
- `op list items --vault "p4n352kzorgonoq2cp4tchgyxe"` (using vault UUID)

I've been wanting to map API onto the entirety of `op`'s CLI functionality, but there's a lot there, so I need to prioritize what's needed first.

**Comment by Tutelajoke** [comment]
The biggest one for us is really just ``op get item "kessel" --vault "Star Wars Planets"``. Another useful bit of functionality buried in ``op`` that is super useful is returning items matching a certain tag(s).
* E.g. We tag all active items with the tag ``active`` and don't want tagged ``inactive`` items to be returned, etc.

In my PowerShell I use a parameter ``[string[]]$tags = @('active')`` and filter the returned JSON for matching tags. Super gross but there you go.

**Comment by Tutelajoke** [comment]
And now that I am coding things maybe you could add ``op signout --forget`` to your list.

By the by this works perfectly in Alpine Docker containers as well. Cheers!

**Comment by zcutlip** [comment]
Sounds good.

Started working on vault support last night. Should have a branch for you to try out soon.

**Comment by zcutlip** [comment]
Can you try out the branch at https://github.com/zcutlip/pyonepassword/tree/dev/support-vaults ?

I may still make some API-breaking changes as I think through a more generalized design, but let me know how this works for you

It should be pretty straightforward, but I updated examples/example-signin-get-item.py with vault usage.

Summary:
- You can pass a default vault to `OP()`
- You can specify a per-query vault to `get_` methods (whether or not you provided a default vault)

**Comment by Tutelajoke** [comment]
This is fantastic. Branch code works like a charm :).

Cheers,
-Adam

**Comment by zcutlip** [comment]
Great. I merged it into master. I'll tag a release soon, but need to get #12 working first.

**Comment by zcutlip** [comment]
you should be able to `pip install 'pyonepassword>=1.7.0'` now

cheers!
