### ISSUE TITLE
Support signout command

### ISSUE THREAD

**Issue by zcutlip** [zcutlip/pyonepassword#12]
As requested in:
https://github.com/zcutlip/pyonepassword/issues/11#issuecomment-713130157

Support `op signout` command.

**Comment by zcutlip** [comment]
@Tutelajoke can you give signout() a try in the branch:
https://github.com/zcutlip/pyonepassword/tree/dev/support-signout

Example in `examples/example-signin-signout.py`

**Comment by Tutelajoke** [comment]
Ran like a dream :). Thank you for digging into this so fast!

**Comment by zcutlip** [comment]
Excellent. Merged in to master.

I need to make some small updates to the readme & examples and then I'll cut a release
