### ISSUE TITLE
Unable to retrieve items using Service Account

### ISSUE THREAD

**Issue by projx** [zcutlip/pyonepassword#127]
Hi

I'm attempting to use the new 1Password Service Account to pull back secret my script, and I'm not sure why its failing.  

```
import dotenv
from pprint import pprint
from pyonepassword import OP


dotenv.load_dotenv("../.token.env")
op = OP()
item = op.item_get("test", relaxed_validation=True)

pprint(item["fields"])
```
What I get back is:

```
Traceback (most recent call last):
  File "/Users//Prog/packer/stubs/1pass.py", line 86, in <module>
    main()
  File "/Users//Prog/packer/stubs/1pass.py", line 56, in main
    item = op.item_get("op://zKUBE - MGT/test/password", relaxed_validation=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users//Prog/virtualenvs/packer/lib/python3.11/site-packages/pyonepassword/pyonepassword.py", line 169, in item_get
    output = super()._item_get(item_identifier, vault=vault,
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users//Prog/virtualenvs/packer/lib/python3.11/site-packages/pyonepassword/_py_op_commands.py", line 528, in _item_get
    output = self._run_with_auth_check(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users//Prog/virtualenvs/packer/lib/python3.11/site-packages/pyonepassword/_py_op_commands.py", line 413, in _run_with_auth_check
    raise OPSvcAcctCommandNotSupportedException(err_msg)
pyonepassword._svc_account.OPSvcAcctCommandNotSupportedException: Command or subcommand not supported: [item get op://zKUBE - MGT/test/password]
```
The service account has **full** access to the vault, I've tried other combos (including passing vault="zKUBE - MGT")... and the token successful reads items, when I use it direct with the op cli command:

```
> op read 'op://zKUBE - MGT/test/password'                                                                  
TestPassword
```

I'd really appreciate if you could point me in the right direction.

**Comment by zcutlip** [comment]
I sorry for the slow response.

In the case you pasted in above, you need to pass a `vault=` kwarg to `item_get()` since service accounts require the vault be specified.

However you said you've also tried it with the vault specified and it's also failing? I'm wonder if you can give me some details about that in case it's a different error.

**Comment by zcutlip** [comment]
You can read more about what operations are and aren't supported with service accounts, as well as exceptions `pyonepassword` might raise here:
https://github.com/zcutlip/pyonepassword/blob/main/docs/AUTHENTICATION.md#service-accounts

**Comment by zcutlip** [comment]
oh also, I don't think `"op://zKUBE - MGT/test/password"` is going to work as an item identifier. whatever you pass in to `OP.item_get()` must also work with `op item get` on the command line.

For the most part I think this is going to be an item UUID or item name. Check out `op item get --help` for more details

`pyonepassword` does have API that makes it easy to retrieve a password field, but it doesn't support the `op read` special URLs like you were using above

You should be able to do something like:

```python
item = op.item_get("test", vault="Your Vault")
password = item.password
```

Or you can use the convenience function:

```python
password = op.item_get_password("test", vault="Your Vault")
```

Also, when debugging, it can help to turn on some logging so we can see what's getting executed, and also see any errors given by `op`:

```python
import os

from pyonepassword import OP, logging

# tell pyonepassword to log errors to the console
os.environ['LOG_OP_ERR'] = "1"

# get a console logger
logger = logging.console_logger("whatever_name", logging.DEBUG)

# pass the logger to OP()
op = OP(logger=logger)
```

Let me know if any of that gets you going, and feel free to share with me any errors you get

**Comment by zcutlip** [comment]
Hey @projx let me know if the above remarks get you going

I'll close this issue in a few days if I don't hear back

**Comment by projx** [comment]
Thanks for this, I've got it working, much appreciated.
