### ISSUE TITLE
Support forgetting arbitrary account details

### ISSUE THREAD

**Issue by zcutlip** [zcutlip/pyonepassword#13]
Issue #12 adds support for `op signout` as well as `op signout --forget`. But not `op forget <account>`.

You can't `op forget` an account from within that account's session. So we need a class method:
`OP.forget(account)`
so you can forget out arbitrary accounts without signing in first.

But to do this, `OP._run()` needs to be a class method.

**Comment by zcutlip** [comment]
@Tutelajoke if you have a chance and this is useful for you would you mind looking at the branch at https://github.com/zcutlip/pyonepassword/tree/dev/support-forget

- Supports forgetting arbitrary accounts
- No active session required
- Class method, so no `OP` instance required
- Example in `examples/example-signin-forget.py`

**Comment by zcutlip** [comment]
Merged into master and tagged as version 1.7.1

**Comment by Tutelajoke** [comment]
Apologies for the delay. Been a busy time of the year. Looks great and thank you again for this!

**Comment by zcutlip** [comment]
You bet! Do let me know if you need anything else or of anything breaks.
