### ISSUE TITLE
Support editing items

### ISSUE THREAD

**Issue by zcutlip** [zcutlip/pyonepassword#143]
### Discussed in https://github.com/zcutlip/pyonepassword/discussions/140

<div type='discussions-op-text'>

<sup>Originally posted by **tdb** July 20, 2023</sup>
How can I edit items? It looks like the `op` command itself supports this:

https://developer.1password.com/docs/cli/reference/management-commands/item/#item-edit

I suppose I could get the item, modify it, delete the original, then recreate it? But that doesn't seem like the right approach.

Maybe I'm missing something?</div>

**Comment by zcutlip** [comment]
As discussed in #140, I think I can support a restricted API that allows specific edits to specific fields, such as updating passwords or changing item titles.

**Comment by zcutlip** [comment]
Somehow I'm only now realizing that `op item edit` has a few convenience CLI options that don't require the `[<section>.]<field>[[<fieldType>]]=<value>` syntax.

These include:

- `--generate-password`
- `--tags`
- `--title`
- `--vault`, and...
- to some degree `--autofill-urls`, though that one's a bit complicated

This should make it much easier to add some basic item editing than I'd anticipated.

To set a specific password rather than have it autogenerated, I'll still need to do the section/field/type/value syntax under the hood, but it shouldn't be too bad.

**Comment by zcutlip** [comment]
I also discovered that `--format JSON` causes `op item edit` to output the complete updated item object. So this means I should be able to return a proper `OPAbstractItem` object for the caller to inspect if desired.

Additionally, there's a `--dry-run` flag. I haven't experimented with it yet, but I suspect I can expose that in the API so the caller can inspect the resulting `OPAbstractItem` object before actually making the change.

**Comment by zcutlip** [comment]
I've got an initial version of password editing working, @tdb. Currently it only supports generating a new password from a password recipe.

here's an example changing the password and showing the old and new passwords:
```python-repl
In [1]: from pyonepassword import OP, logging

In [2]: from pyonepassword.api.constants import LETTERS_DIGITS_SYMBOLS_20

In [3]: logger = logging.console_logger("ipython", logging.DEBUG)

In [4]: op = OP(logger=logger)
Running: op --version
Running: op --format json account list
Running: op signin --raw
Running: op --format json whoami
Signed in as User ID: *********************ERLHI

In [5]: item_name = "Edit Login Password"

In [6]: item = op.item_get(item_name)
Running: op --format json whoami
Running: op --format json item get 'Edit Login Password'

In [7]: item.password
Out[7]: 'old crappy password'

In [8]: item = op.item_edit_generate_password(item_name, LETTERS_DIGITS_SYMBOLS_20)
Running: op --format json whoami
Running: op --format json item edit 'Edit Login Password' --generate-password=20,letters,digits,symbols

In [9]: item.password
Out[9]: 'RsVz3U3XJQRP64a*3XNR'
```

There are a couple of recipe constants defined in `pyonepassword.api.constants`, or you can define your own with `pyonepassword.api.object_types.OPPasswordRecipe`.

Also this operation is not currently registered as supporting service accounts, but I'll add that before I'm done

**Comment by zcutlip** [comment]
have field assignment construction working here:
https://github.com/zcutlip/pyonepassword/blob/dev/143-support-editing-items/pyonepassword/_field_assignment.py

I think I'm doing proper escaping, per the `op` CLI documentation:

```
In [1]: from pyonepassword._field_assignment import _FieldAssignment, FieldTypeEnum

In [2]: fl = "weird=password.field_label"

In [3]: sl = "my_section"

In [4]: value = "dumb password"

In [5]: field_type = FieldTypeEnum.PASSWORD

In [6]: assignment = _FieldAssignment(fl, value, field_type=field_type, section_label=sl)

In [7]: print(assignment)
my_section.weird\=password\.field_label[password]=dumb password
```

**Comment by zcutlip** [comment]
@tdb, @gadgetgeekni, I've got two forms of password editing working in the branch `dev/143-support-editing-items`.

The first lets you have 1Password generate a new password. It uses `--generate-password` under the hood and only works on the field named "password" as a login item would have.

e.g.,:
```
item = op.item_edit_generate_password(item_name, LETTERS_DIGITS_SYMBOLS_20)
```

The second form lets you explicitly set a password. This lets you set a password field with a nonstandard name that is optionally a member of a section.

This form uses the `<section>.<field>[password]=<new password>` syntax under the hood, which means it's inherently insecure, since the password is part of the plaintext command-line arguments. As such, the caller must acknowledge & accept this risk by passing `insecure_operation=True`:

e.g.,:
```
item = op.item_edit_set_password(item_name, new_password, insecure_operation=True)
```

Currently item_edit_set_password() will add a new field if you specify a field or section name that doesn't exist. I intend to prevent this behavior to prevent field/section typos from creating new fields accidentally. But I expect to add some kind of `item_edit_set_new_field()` capability for those who need it.

If you get a chance, please give these a try and let me know how they go.

**Comment by zcutlip** [comment]
also worth noting, if you pass a debug logger into `OP()` so that commands get logged before they're executed, the assignment string is self-redacting if it's a password assignment:

```
In [4]: item = op.item_edit_set_password(item_name, new_password, insecure_opera
   ...: tion=True)
Running: op --format json whoami
Running: op --format json item edit 'Edit Login Password' 'password[password]🟰********************'

In [5]:
```

**Comment by zcutlip** [comment]
Per `op` documentation setting values on fields where the field and/or section doesn't exist will cause the field/section to be created

This means if there's a typo in the field and/or section name, rather than changing an existing field, a new field (and possibly section) would silently be created. Therefore, we will fetch the item and validate the field and section where appropriate before calling "op item edit"

However, in implementing this, I realized that we're really inconsistent with how we handle looking up missing fields and sections on op item objects

I'm addressing this in #144 first in support of this issue

**Comment by zcutlip** [comment]
Current set of implemented item-edit features includes:
- `OP.item_edit_generate_password()`
- `OP.item_edit_set_password()`
- `OP.item_edit_set_title()`
- `OP.item_edit_set_favorite()`
- `OP.item_edit_set_tags()`

A couple notes:
- `item_edit_set_password()` checks that the field (and section if specified) exist on the object before setting the new password
- `item_edit_set_tags()` currently replaces the existing set of tags, which is the behavior `op item edit --tags`
  - I'm considering adding an optional `replace=` kwarg so the caller can choose to either replace (probably the default) or append
  - This will have the implication of optionally doing an `item_get()` first
  - This also will have an implication for service accounts since a SA requires a vault to be specified for `item get` but not (for some reason) for `item edit`

All of the above continues to be available in the `dev/143-support-editing-items` branch

**Comment by zcutlip** [comment]
`OP.item_edit_set_tags()` now has an `append_tags` kwarg which defaults to False. When False, tags are replaced (possibly with an empty list), when True, tags are appended to

As described above, this has the following implications:

- if `append_tags` is True, this results in an  `op item get` operation to retrieve the original set of tags. This operation does not happen if `append_tags` is False
- When using a service account as it stands currently, the vault option is required only if append_tags is True, which is unintuitive
- Documenting a method's service account compatibility as `required keyword arguments: vault sometimes but it depends` is suboptimal, so there are a couple options:
- Document service account compatibility as `vault` arg required, and just have it be a wart that sometimes things work out okay even when they shouldn't
- Perform the `item get` operation unconditionally, which will have the following benefits:
  - service account checking (and possibly failing) will be uniform regardless of tag appending
  - If the item can't be found, you get the same exception you get when calling `OP.item_get()` directly, which is a nice congruence

**Comment by zcutlip** [comment]
I guess another option would be to have a discrete method like `item_edit_append_tags()` that always behaves the same way, leaving `item_edit_set_tags()` to also always behave the same way, but the OP class is already kind of exploding, so idk....

**Comment by zcutlip** [comment]
`OP.item_edit_set_url()` is now complete

**Comment by GadgetGeekNI** [comment]
Thank you for this! I can't wait to see it in action. 

I am building out a python script at the moment and the use case will be to update the rotated_credential and accessor_id fields from an item.
Thank you for your efforts on this!

**Comment by zcutlip** [comment]
@GadgetGeekNI you bet. please do give it a try from the feature branch if you're able (let me know if you'd like me to roll up a release for you to try)

This is going to be significant 4.0 release. I'm nearing the end but there are a few issues remaining that are a bit thornier than one might guess

**Comment by zcutlip** [comment]
@GadgetGeekNI if you're able to could you share before & after JSON from example items you're editing?

If you're able to do an `op --format item get` before and after and sanitize any sensitive text, that would be great.

**Comment by zcutlip** [comment]
Sorry for the lack of updates here, but if you follow the commits in the `dev/143-support-editing-items` branch I've been steadily working on things. There have been a lot of considerations that weren't obvious at first

Many of these revolve around `op` being someone loose and unpredictable with `item edit` operations. 

This includes what `op` does when you try to edit items where the JSON doesn't conform to the standard format (see #88 for info on non-conforming items). It also includes how `op` handles field editing when field label matching may be ambiguous

At any rate, I've release a beta, `4.0.0b0` because there are lots of changes and I hope someone's interested in kicking the tires

Here's API that's been added:

- Item editing:
  - `OP.item_edit_generate_password()`
  - `OP.item_edit_set_password()`
  - `OP.item_edit_set_title()`
  - `OP.item_edit_set_favorite()`
  - `OP.item_edit_set_tags()`
  - `OP.item_edit_set_url()`
  - `OP.item_edit_set_text_field()`
  - `OP.item_edit_add_text_field()`
  - `OP.item_edit_set_url_field()`

- `OPAbstractItem.field_value_by_section_label()` as a replacement for poorly named `field_value_by_section_title()`

You can see more information in the CHANGELOG under this beta release:
https://github.com/zcutlip/pyonepassword/releases/tag/v4.0.0b0

This release is not yet feature complete but what has been added should be fairly well tested. I plan to add a few more `item_edit` methods for adding add deleting additional fields.

You should be able to install it with `pip3 install --pre pyonepassword`

**Comment by zcutlip** [comment]
beta `v4.0.0b1` released on pypi. Only change is to actually remove python 3.8 from setup.py

**Comment by zcutlip** [comment]
added `OP.item_edit_add_password_field()`

**Comment by zcutlip** [comment]
added a bunch of test cases for item-edit error handling

**Comment by zcutlip** [comment]
added `OP.item_edit_delete_field()`

still need to add tests for this

**Comment by zcutlip** [comment]
Here's pretty close to final documentation for item editing:
https://github.com/zcutlip/pyonepassword/blob/dev/143-support-editing-items/docs/item-editing.md

**Comment by zcutlip** [comment]
Added `OP.item_edit_add_url_field()`

I think everything should be complete for item editing at this point. I'm going to merge this branch into development and close out this issue.

There's still a bit of cleanup work to do which I'll do in the development branch.

**Comment by zcutlip** [comment]
This is complete as of pr #168, v4.0.0.

You may get v4.0.0 via PyPI:

`pip3 install pyonepassword --upgrade "pyonepassword>=4.0.0"`

cc: @tdb
