### ISSUE TITLE
How to access section data?

### ISSUE THREAD

**Issue by iainelder** [zcutlip/pyonepassword#18]
I didn't see an example for this in the documentation.

Is there a cleaner way than direct access to the items dict?

```python
from getpass import getpass
from pyonepassword import OP

master_password = getpass("1Password master password: ")
op = OP(password=master_password)

item = op.get_item("Sample Item")
fields = item._item_dict["details"]["sections"][0]["fields"]
value = [f["v"] for f in fields if f["t"] == "Sample Field"][0]

print(value)
```

**Comment by zcutlip** [comment]
There are a few methods that might be useful for you.

Any class that extends `OBAbstractItem` has:

- `def field_value_by_section_title(self, section_title: str, field_label: str)`
- `def first_section_by_title(self, title) -> OPSection`
- `def sections_by_title(self, title) -> List[OPSection]`

Note that `field_value_by_section_title()` returns the field value from the first matching section. If you have duplicate section titles and need a different one, use `sections_by_title()` to get a list of matching sections. Then you can operate on each `OPSection`, and each section/s `OPSectionField`.

Apologies, I haven't updated documentation in a while; I need to get on that.

There's an example in `ssh-server-keys.py`:
https://github.com/zcutlip/pyonepassword/blob/7ae948db4689bbebe6ea39a0be63c2d9774631e0/examples/server-ssh-keys.py#L17

Let me know if that helps!

**Comment by iainelder** [comment]
Unfortunately it's not working for me with this item type.

```python
item.field_value_by_section_title("Sample Section", "Sample Field")
```

The function isn't available.

```text
AttributeError: 'OPLoginItem' object has no attribute 'field_value_by_section_title'
```

Here's what I get from `dir(item)`:

```python
['TEMPLATE_ID',
 '__abstractmethods__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__slots__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_abc_impl',
 '_item_dict',
 'get_item_field_value',
 'password',
 'title',
 'username',
 'uuid']
```

I'm using version 1.8.3 installed from PyPI, in case that matters.

**Comment by zcutlip** [comment]
Sorry about that. I didn't realize I hadn't tagged a release for those latest changes.

You should be able to get v1.9.0 from pypi now. It's tested extremely lightly because I wanted to go ahead and get it up there so you could use it. Let me know if anything breaks for you.

Also let me know if you need any further API. I have a number of plans in the pipeline that I just need to make time for. If there's something you need that I have planned, that'll help me prioritize.

**Comment by iainelder** [comment]
> You should be able to get v1.9.0 from pypi now.

Just got it! Thanks.

Unfortunately it's unusable for me. The very first import fails!

```text
>>> import pyonepassword
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".../lib/python3.8/site-packages/pyonepassword/__init__.py", line 7, in <module>
    from .op_items.login import OPLoginItem
ModuleNotFoundError: No module named 'pyonepassword.op_items'
```

**Comment by zcutlip** [comment]
Ugh, I'm really sorry. That's what I get for taking shortcuts. I wasn't picking up the new `op_items` subpackage in setup.py

I've fixed that and updated tests

You should be able to `pip install` v1.9.1 now

Let me know if this gets you going, and thank you for your patience

**Comment by iainelder** [comment]
Perfect! The field_value_by_section_title method now works as expected.

> thank you for your patience

Thank you for your effort! This library is a lot better that what I have the patience or experience to build by myself. Before I discovered it I was using Pexpect to wrap just the commands I needed.

> Also let me know if you need any further API

I need a way to create new items to be able to complete my workflow using Python.

Example:

* Read a template containing all the configuration (from 1Password using pyonepassword)
* Use the configuration to drive a script to create an account on a website (driving Firefox via Selenium)
* Save the new account's credentials in 1Password (to 1Password using ... pyonepassword, I hope!)

Do you want me to create a new issue for that?

**Comment by zcutlip** [comment]
Yes, item creation has been on my list for a while. It's a bit trickier than simply reading objects out.

I'll give it a look because I need it too. Please create an issue.

Going to go ahead and close this issue
