### ISSUE TITLE
Add API to create items

### ISSUE THREAD

**Issue by iainelder** [zcutlip/pyonepassword#20]
I need a way to create new items to be able to complete my workflow using Python.

Example:

* Read a template containing all the configuration (from 1Password using pyonepassword)
* Use the configuration to drive a script to create an account on a website (driving Firefox via Selenium)
* Save the new account's credentials in 1Password (to 1Password using ... pyonepassword, I hope!)

**Comment by zcutlip** [comment]
A few questions:

- Can you clarify "template containing all the configuration"? What configuration are you referring to?
- I'll probably tackle creating easy item types first (some are very complex), such as type `001` - `login`. Are there other item types you need (see `op list templates`)?

**Comment by iainelder** [comment]
By "template containing all the configuration" I mean I use a 1Password item to store all the reusable data for account creation. Name, address, billing details, that sort of thing. To create a new user account the script would get the item and combine the reusable data with a unique user name and password.

You don't need to do anything there. 1Password already handles it.

At a minimum, I need to save an email address and a password. It would be helpful to save an account name in a field as well, but it is not necessary. I would probably set the account name as the item name in any case. I think the template `{"uuid":"001","name":"Login"}` would cover it.

**Comment by zcutlip** [comment]
I've been working on this, and you can try it out in the `dev/item-creation` branch.

A couple of notes:

- Unfortunately, item create is insecure do to how the `op` command works, see discussion here:
  - https://1password.community/discussion/comment/604875/#Comment_604875
 - There doesn't appear to be a way to associate website URLs with a login item at time of creation; see discussion here:
   - https://1password.community/discussion/122162/creating-new-login-item-including-website-url
- I'm not super happy with this API as-is so expect it to change some

Here's an example of item creation:
```Python
def main():
    op = do_signin()
    username = "zach"
    password = "zachpass"
    newlogin = OPLoginItemTemplate(username, password)

    # user-visible section name is required
    # section title is optioanl and will be randomly generated if not provided
    section = newlogin.add_section("New Section")

    # field name is not user visible
    # field title is user visible
    section.add_field("example field name", "example value", "string", "example field label")

    try:
        result = op.create_item(newlogin, "login 3")
    except OPCmdFailedException as e:
        print("create_item() failed")
        print(e.err_output)
        return e.returncode
```

**Comment by zcutlip** [comment]
The above example creates the following 1Password entry:

<img width="614" alt="Screen Shot 2021-07-24 at 10 16 02 AM" src="https://user-images.githubusercontent.com/2158303/126876209-43fb5e6b-90aa-4565-9903-a3d8429b1e84.png">

**Comment by zcutlip** [comment]
And here's the under the hood JSON, if you query the newly created "login 3"
```JSON
{
  "uuid": "x2ougtjfmhi5dndmlkg27wqpiy",
  "templateUuid": "001",
  "trashed": "N",
  "createdAt": "2021-07-24T17:15:33Z",
  "updatedAt": "2021-07-24T17:15:33Z",
  "changerUuid": "RAXCWKNRRNGL7I3KSZOH5ERLHI",
  "itemVersion": 1,
  "vaultUuid": "yhdg6ovhkjcfhn3u25cp2bnl6e",
  "details": {
    "fields": [
      {
        "designation": "username",
        "name": "username",
        "type": "T",
        "value": "zach"
      },
      {
        "designation": "password",
        "name": "password",
        "type": "P",
        "value": "zachpass"
      }
    ],
    "notesPlain": "",
    "passwordHistory": [],
    "sections": [
      {
        "fields": [
          {
            "k": "string",
            "n": "example field name",
            "t": "example field label",
            "v": "example value"
          }
        ],
        "name": "Section_6F1F96368DBC4DAEAFBB06A509E02019",
        "title": "New Section"
      }
    ]
  },
  "overview": {
    "ainfo": "zach",
    "ps": 16,
    "title": "login 3"
  }
}
```

**Comment by zcutlip** [comment]
Okay, it looks like you can specify the `--url` option to the `op` command when creating login items. I'd missed that earlier. It only supports a single URL though, so creating a login item that is valid for more than one URL doesn't sound possible.

Discussion here:
https://1password.community/discussion/comment/605261/#Comment_605261

**Comment by iainelder** [comment]
Just back from vacation. I'll check out the new branch this week and let you know how it works for me. :-)

> item creation is insecure due to how the op command works

Yeah, I created that thread before requesting the feature here. I didn't link it because I hadn't received a response yet from 1Password. Thanks for following up!

We can look forward to the 1Password team improving the secure input for secrets.

The way it works just now is fine for my purposes.

**Comment by zcutlip** [comment]
> Yeah, I created that thread before requesting the feature here

Oh cool, didn't realize that was you.

I think they'll fix it eventually, but I'm going to add a boolean kwarg, requiring the caller to acknowledge the insecurity. An exception will be raised without it.

**Comment by iainelder** [comment]
> Just back from vacation. I'll check out the new branch this week

How time flies... Sorry for the delay!

I just tried your example and I'm getting stuck at a NameError.

```text
$ python main.py
1Password master password:

Using account shorthand found in op config: my
Doing normal (non-initial) 1Password sign-in
Traceback (most recent call last):
  File "main.py", line 45, in <module>
    main()
  File "main.py", line 15, in main
    newlogin = OPLoginItemTemplate(username, password)
NameError: name 'OPLoginItemTemplate' is not defined
```

I tried to import OPLogItemTemplate, but I couldn't find it anywhere in the code.

My main.py contains:

```python
import getpass

from pyonepassword import (  # noqa: E402
    OP,
    OPSigninException,
    OPGetItemException,
    OPNotFoundException,
    OPConfigNotFoundException
)

def main():
    op = do_signin()
    username = "zach"
    password = "zachpass"
    newlogin = OPLoginItemTemplate(username, password)

    # user-visible section title is required
    # section name (not user visible) is optional and will be randomly generated if not provided
    section = newlogin.add_section("New Section")

    # field name is not user visible
    # field label is user visible
    section.add_field("example field name", "example value", "string", "example field label")

    try:
        result = op.create_item(newlogin, "login 3")
    except OPCmdFailedException as e:
        print("create_item() failed")
        print(e.err_output)
        return e.returncode


def do_signin():
    # If you've already signed in at least once, you don't need to provide all
    # account details on future sign-ins. Just master password
    my_password = getpass.getpass(prompt="1Password master password:\n")
    # You may optionally provide an account shorthand if you used a custom one during initial sign-in
    # shorthand = "arbitrary_account_shorthand"
    # return OP(account_shorthand=shorthand, password=my_password)
    # Or we'll try to look up account shorthand from your latest sign-in in op's config file
    return OP(vault="Test Data", password=my_password)


if __name__ == "__main__":
    main()
```

**Comment by zcutlip** [comment]
Okay, sorry about that. 

I've considerably refactored the item creation API, so pull `dev/item-creation`, and try out `examples/create-item.py`.

Some notes:

- `OP` objects now have a `create_login_item_` convenience method
- There is also a `create_item_` method that takes an OPAbstractItem object created from template
- You can only create an item with a single URL, even though login items can support multiple URLs
  - this is a limitation of the `op` CLI tool
- Both methods query the item just created and return the result
- To create items, you have to pass `acknowledge_insecurity=True` (due to https://github.com/zcutlip/pyonepassword/issues/20#issuecomment-887603878)
- The `create_login_item_`, `create_item_` are specially named in anticipation of deprecation once the `op` CLI tool can create items securely

**Comment by zcutlip** [comment]
This is officially supported in 2.0 as of e4d32b.

**Comment by iainelder** [comment]
Hi, @zcutlip , thanks for you work on this. I'm sorry that I haven't given much feedback lately. The side project that would benefit from this is on hold just now. When I come back to it I'll definitely give this a shot!

**Comment by zcutlip** [comment]
> The side project that would benefit from this is on hold just now. When I come back to it I'll definitely give this a shot!

No worries @iainelder. When you do, just let me know if you have any issues or feedback
