### ISSUE TITLE
(re-)Add item creation support

### ISSUE THREAD

**Issue by zcutlip** [zcutlip/pyonepassword#36]
Item creation support was temporarily removed in version 3.0.0. 

Let's re-think how it should work and add it back.

**Comment by zcutlip** [comment]
work underway in the [dev/support-item-creation-again](https://github.com/zcutlip/pyonepassword/tree/dev/support-item-creation-again) branch

**Comment by nodomain** [comment]
Oops I just found this on my search for how to create/add an item. I need this for my use case... can it be used already?

**Comment by zcutlip** [comment]
It's currently usable but I'm still in the process of testing. Also, I only have support for 'login' item types at the moment (others will be easy to add, but I wanted to get this one working first)

If you want to try it, check out the branch referenced above? It's under active development, so beware.

I hope to do a release soon.

**Comment by zcutlip** [comment]
I pushed an example of item creation. It's pretty basic and there's a lot more you can do, such add custom fields & sections, etc. But for simple login items, the convenience API is pretty straightforward.
https://github.com/zcutlip/pyonepassword/blob/48ed6ef2de4d4a6e781f0acb5a51c26bf8e845c6/examples/example-create-item.py

**Comment by nodomain** [comment]
Thanks, this should be fine for my use case. I'll have a look!

**Comment by zcutlip** [comment]
Also be aware the API is still in flux, so things will probably change.

**Comment by nodomain** [comment]
I managed to create an item in my desired vault 👍 

If I now could add an OTP field into it, my task is fulfilled. Can you please point me into the right direction?

**Comment by zcutlip** [comment]
At the moment, there isn't a straightforward way to do it, but depending on exactly what you need, it might not be too hard to add.

Please file a separate issue, and we can talk about it some more

**Comment by nodomain** [comment]
#45

**Comment by zcutlip** [comment]
this has been merged into development branch via #51. closing issue
