### ISSUE TITLE
Add TOTP during item creation

### ISSUE THREAD

**Issue by nodomain** [zcutlip/pyonepassword#45]
When creating a login item I want to add the TOTP data as well for 2FA protected logins. 

Background: I maintain AWS IAM accounts with virtual MFA devices using a Python script that are only used as emergency login if our central OIDC based "token machine" has an outage. 
The credentials of the accounts shall be stored (and updated after key and password rotation) in 1Password.

**Comment by zcutlip** [comment]
Actually I guess it's more often, like:

```
otpauth://totp/<website>:<user>?secret=<secret>&issuer=<issuer>
```

**Comment by nodomain** [comment]
Yes I am.

In my use case I generate IAM users with virutal MFA devices and I am able to reconstruct the `otpauth` URL that is used to generate the provided QRCode: https://docs.aws.amazon.com/IAM/latest/APIReference/API_VirtualMFADevice.html

Example:

```python
account_id = session.client('sts').get_caller_identity().get('Account')
username = os.environ.get('EMERGENCY_USER_NAME')
string_seed = mfa_device['VirtualMFADevice']['Base32StringSeed']
string_seed_str = string_seed.decode("utf-8")
otpauth_url = 'otpauth://totp/Amazon%20Web%20Services:' + username + '@' + account_id + '?secret=' + string_seed_str + '&issuer=Amazon%20Web%20Services'
```

So in order to end up with an item like this:
<img width="707" alt="Bildschirmfoto 2022-10-18 um 20 32 05" src="https://user-images.githubusercontent.com/104389/196515214-e8bf14f6-c1cb-4a42-a69a-5e74a89e04b9.png">

I would need the OTP and an URL (Text?) field.

Furthermore currently I attach a file containing `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY` but I can achieve the same with two more text fields.

Is my assumption correct that this branch then also enables to update existing items? I need to rotate the keys cyclically and it would be great to automate the whole process.

**Comment by nodomain** [comment]
I like your proposal of creating new items after fetching existing ones and deleting them. Cool 😎

**Comment by zcutlip** [comment]
Okay, I've pushed some changes that should let you add a totp field. As before, they're in the [dev/support-item-creation-again branch](https://github.com/zcutlip/pyonepassword/tree/dev/support-item-creation-again) branch.

Look at [examples/example-create-login-with-totp.py](https://github.com/zcutlip/pyonepassword/blob/5c820da3328ecda7ad37d6bd5b05c40ff10f7913/examples/example-create-login-with-totp.py)

Also as before, this branch is still under active development, so APIs are likely to change before it gets merged.

Let me know how it goes!

**Comment by zcutlip** [comment]
Also, I should add this is *very* lightly tested at this point

**Comment by nodomain** [comment]
Thanks for being so responsive! 👀 into it.

Small typo:
https://github.com/zcutlip/pyonepassword/blob/5c820da3328ecda7ad37d6bd5b05c40ff10f7913/examples/example-create-login-with-totp.py#L11
needs to be `OPNewTOTPUri`

**Comment by nodomain** [comment]
I can confirm that your provided solution worked like a charm with the current Git revision!

Next up for me is to implement "get current item, create a new one and delete the old one" for updating the passwords/secrets.

**Comment by zcutlip** [comment]
I'm going to leave this open until I release item creation, which I hope is soon.

Also thank you for the $20 in the tip jar :-)

**Comment by nodomain** [comment]
I wanted to contribute something and I am still on the beginning of my Python journey🍺

**Comment by zcutlip** [comment]
Happy to be on the journey with you :-D

**Comment by zcutlip** [comment]
> Thanks for being so responsive! 👀 into it.
> 
> Small typo:
> 
> https://github.com/zcutlip/pyonepassword/blob/5c820da3328ecda7ad37d6bd5b05c40ff10f7913/examples/example-create-login-with-totp.py#L11
> 
> 
> needs to be `OPNewTOTPUri`

just saw this. I refactored after I posted

**Comment by zcutlip** [comment]
This should be complete as of #51, and is available on the development branch

**Comment by zcutlip** [comment]
@nodomain please note I did change some API from what I pushed a couple weeks ago, so if you pull the development branch, you may need to make some updates to your code
