### ISSUE TITLE
Add support for 'database' item type

### ISSUE THREAD

**Issue by zcutlip** [zcutlip/pyonepassword#98]
We need an `OPDatabaseItem`

This will create a tracking issue for a feature branch, where we can merge @Rom3dius's PRs and I can contribute additional changes such as tests, etc.

**Comment by Rom3dius** [comment]
So, here is the requested JSON dump.

`{'id': 'ess5bravga66ihd6kgpmpdxpz4', 'title': 'Timescale PRD Dummy', 'version': 1, 'vault': {'id': 'o6n2cf54wxahsv56yjxwfj2whm', 'name': 'Private'}, 'category': 'DATABASE', 'last_edited_by': 'CNABSDGMQJHGFIMXS6EKKUPW6M', 'created_at': '2023-03-10T16:43:20Z', 'updated_at': '2023-03-10T16:43:20Z', 'additional_information': 'timescaledb.prd.company.xyz', 'fields': [{'id': 'notesPlain', 'type': 'STRING', 'purpose': 'NOTES', 'label': 'notesPlain', 'reference': 'op://Private/Timescale PRD Dummy/notesPlain'}, {'id': 'database_type', 'type': 'MENU', 'label': 'type', 'value': 'postgresql', 'reference': 'op://Private/Timescale PRD Dummy/type'}, {'id': 'hostname', 'type': 'STRING', 'label': 'server', 'value': 'timescaledb.prd.company.xyz', 'reference': 'op://Private/Timescale PRD Dummy/server'}, {'id': 'port', 'type': 'STRING', 'label': 'port', 'value': '5432', 'reference': 'op://Private/Timescale PRD Dummy/port'}, {'id': 'database', 'type': 'STRING', 'label': 'database', 'value': 'ithas', 'reference': 'op://Private/Timescale PRD Dummy/database'}, {'id': 'username', 'type': 'STRING', 'label': 'username', 'value': 'ithas_admin', 'reference': 'op://Private/Timescale PRD Dummy/username'}, {'id': 'password', 'type': 'CONCEALED', 'label': 'password', 'value': 'totallysecurepassword', 'reference': 'op://Private/Timescale PRD Dummy/password'}, {'id': 'sid', 'type': 'STRING', 'label': 'SID', 'value': 'none', 'reference': 'op://Private/Timescale PRD Dummy/SID'}, {'id': 'alias', 'type': 'STRING', 'label': 'alias', 'value': 'timescale', 'reference': 'op://Private/Timescale PRD Dummy/alias'}, {'id': 'options', 'type': 'STRING', 'label': 'connection options', 'value': '-c work_mem=256MB', 'reference': 'op://Private/Timescale PRD Dummy/connection options'}], 'sections': []}`

And here is the second:

`{'id': 'f6udk24epjreexw2mbxkp25huq', 'title': 'MySQL PRD Dummy', 'version': 1, 'vault': {'id': 'o6n2cf54wxahsv56yjxwfj2whm', 'name': 'Private'}, 'category': 'DATABASE', 'last_edited_by': 'CNABSDGMQJHGFIMXS6EKKUPW6M', 'created_at': '2023-03-10T16:48:39Z', 'updated_at': '2023-03-10T16:48:39Z', 'additional_information': 'mysql.prd.company.', 'fields': [{'id': 'notesPlain', 'type': 'STRING', 'purpose': 'NOTES', 'label': 'notesPlain', 'reference': 'op://Private/MySQL PRD Dummy/notesPlain'}, {'id': 'database_type', 'type': 'MENU', 'label': 'type', 'value': 'mysql', 'reference': 'op://Private/MySQL PRD Dummy/type'}, {'id': 'hostname', 'type': 'STRING', 'label': 'server', 'value': 'mysql.prd.company.', 'reference': 'op://Private/MySQL PRD Dummy/server'}, {'id': 'port', 'type': 'STRING', 'label': 'port', 'value': '3306', 'reference': 'op://Private/MySQL PRD Dummy/port'}, {'id': 'database', 'type': 'STRING', 'label': 'database', 'value': 'nte', 'reference': 'op://Private/MySQL PRD Dummy/database'}, {'id': 'username', 'type': 'STRING', 'label': 'username', 'value': 'root', 'reference': 'op://Private/MySQL PRD Dummy/username'}, {'id': 'password', 'type': 'CONCEALED', 'label': 'password', 'value': 'totallysecurepassword', 'reference': 'op://Private/MySQL PRD Dummy/password'}], 'sections': []}`

Sadly the second doesnt populate all fields, but they're yanked straight out of production with some redacted info.

**Comment by zcutlip** [comment]
awesome, thank you! This really helps. I'll add these to the test corpus.

**Comment by zcutlip** [comment]
completed as of pr #100

**Comment by zcutlip** [comment]
@Rom3dius just wanted you to know in case it's useful, there's now support for database item creation as of v3.8.0. Just create an `OPDatabaseItemTemplate` object, and pass it to `OP.item_create()`
